### ISSUE TITLE
TODO for next deploy

### ISSUE THREAD

**Issue by leafo** [leafo/sightreading.training#32]
- [ ] Redesign the playalong page
- [ ] Add song visibility options
- [ ] Editing someone else's song will create a copy on your account
- [ ] Add banner about enabling sound

**Comment by dharness** [comment]
Time spent would be awesome! Especially in staff mode, it would be nice to know my rolling notes/minute or my notes/min/day.

It would also be nice to start/stop a session to make that time meaningful or even decide on a pre-determined amount of time - say, I want to do a 15 minute chunk of practice

**Comment by leafo** [comment]
@dharness the time recording thing I'm planning will record in 30 second chunks, so if you do at least one thing per 30 seconds it will continue to record time practicing. I think that should be accurate enough, and doesn't require any advanced code to measure times spent. I was only going to add it for play-along mode for the initial launch.

As for having timed practice sessions, I like that idea. I was thinking of putting together something where you could build practice regimen where you make presets of practice configurations, and set them up in a series where each one will show shown for some amount of time.

**Comment by dharness** [comment]
@leafo the 30s chunk patter would definitely meet my use case! Though as mentioned I would want it in staff mode since I think play-along is harder and I'm not at that level yet.

Practice regimens are even better! Thanks for your great work.
